#!/bin/bash


clear
export FOLDER=4hf-corona
export FRONT_FOLDER=$FOLDER/4hf-corona-front
export DOMAIN=alenalic.nl
export SUBDOMAIN=4hfcorona.$DOMAIN
export API_SUBDOMAIN=api.$SUBDOMAIN;

echo "SETTINGS"
echo "========="
echo "folder:"
echo $FOLDER
echo "domain:"
echo $DOMAIN
echo "========="
echo ""

echo "install demo? (y/n)"
read continue
if [[ $continue = "y" ]]
then


echo "Installing git repository====================="
cd
mkdir $FOLDER
cd $FOLDER
git clone https://github.com/AlenAlic/4hf-corona-front
echo "Installing git repository complete============"


echo "Setting up config============================="
cd && cd $FRONT_FOLDER
bash -c 'cat > public/config/config.json' << EOL
{
    "cookies": {
        "enabled": true,
        "type": "banner"
    },
    "api": {
        "url": "https://$API_SUBDOMAIN/api"
    }
}
EOL
echo "Setting up config complete===================="


echo "Build frontend================================"
cd && cd $FRONT_FOLDER
npm install
npm run build
echo "Building complete============================="


echo "Setting up nginx=============================="
sudo -E bash -c 'cat > /etc/nginx/conf.d/$SUBDOMAIN.conf' << EOL
server {
    listen 443 ssl http2;
    server_name $SUBDOMAIN;
    location / {
        root /home/$USER/$FRONT_FOLDER/dist;
        index index.html;
        try_files \$uri \$uri/ /index.html;
    }
    access_log /var/log/$SUBDOMAIN.access.log;
    error_log /var/log/$SUBDOMAIN.error.log;
    ssl_certificate /etc/letsencrypt/live/$SUBDOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$SUBDOMAIN/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_ecdh_curve secp521r1:secp384r1:prime256v1;
}
server {
    server_name $SUBDOMAIN;
    return 301 https://\$host\$request_uri;
}
EOL
sudo service nginx reload
echo "Setting up nginx complete====================="


echo "Creating update script========================"
cd && cd $FRONT_FOLDER
bash -c 'cat > scripts/update' << EOL
cd && cd $FRONT_FOLDER
echo "Checking out new version===="
git pull
echo "========================Done"
echo "Building frontend==========="
npm install
npm run build
echo "========================Done"
echo "Restarting Services========="
sudo systemctl reload nginx
echo "========================Done"
cd
EOL
echo "Created update script========================="


echo "Creating update scripts======================="
cd
echo "alias 4hf-corona-front-update='cd && source $FRONT_FOLDER/scripts/update'" >> .bashrc
source .bashrc
echo "Created update scripts========================"


else
echo "Skipping DEMO installation."
fi
cd
